### ISSUE TITLE
face-detection-retail-0004 only returning a single high-confidence match

### ISSUE THREAD

**Issue by itsderek23** [luxonis/depthai-tutorials#1]
While working on the 3rd tutorial, I'm seeing an issue with the `face-detection-retail-0004` model where it only returns one high-confidence face match per model inference. 

For example, this is the result of 2 consecutive runs of `nnet_packet.entries()`. I'm grabbing entries where the label == 1 (a face) and printing some of the details. 

# First Inference

```
['label=1 conf=1.0 x_min=0.60205078125', 'label=1 conf=0.03125 x_min=0.9716796875', 'label=1 conf=0.029296875 x_min=0.810546875', 'label=1 conf=0.02587890625 x_min=0.80712890625', 'label=1 conf=0.02392578125 x_min=0.0662841796875', 'label=1 conf=0.02294921875 x_min=0.10748291015625', 'label=1 conf=0.02197265625 x_min=0.8544921875', 'label=1 conf=0.02099609375 x_min=0.9189453125', 'label=1 conf=0.02001953125 x_min=0.783203125', 'label=1 conf=0.01904296875 x_min=-0.0291748046875']
```
# 2nd inference

```
['label=1 conf=1.0 x_min=0.2109375', 'label=1 conf=0.029296875 x_min=0.0133819580078125', 'label=1 conf=0.02734375 x_min=0.1114501953125', 'label=1 conf=0.02490234375 x_min=0.118408203125', 'label=1 conf=0.02392578125 x_min=0.5908203125', 'label=1 conf=0.02294921875 x_min=0.9521484375', 'label=1 conf=0.02197265625 x_min=0.900390625', 'label=1 conf=0.02099609375 x_min=0.94384765625', 'label=1 conf=0.02001953125 x_min=0.78466796875', 'label=1 conf=0.01904296875 x_min=0.1085205078125']
```

# Analysis

While holding two faces in a stationary position, the first inference detects one face at x_min = 0.60205078125. The second detects one face at x_min = 0.2109375.

I'm not able to detect both faces at once w/high confidence even though they each return with 100% confidence by themselves. I'd expect to see an entry for each (two total high-confidence matches) in every inference.

I'm also seeing the same behavior w/the model of the same name within `depthai-python-extras`. 

# Open Question

__Is this an issue w/the model itself or something within DepthAI?__ I may try running [this demo app](https://github.com/opencv/open_model_zoo/tree/master/demos/python_demos/face_recognition_demo) to see see if I see the same behavior. If I do, it's likely the model itself.

If it is with the model itself, it may make sense to pick another pre-trained model with a 300x300 output shape.

**Comment by itsderek23** [comment]
Noticed that the demo app [isn't available in Open Model Zoo 2019_R2](https://github.com/opencv/open_model_zoo/tree/2019_R2/demos/python_demos). It first appears in [2019_R3](https://github.com/opencv/open_model_zoo/tree/2019_R3/demos/python_demos). May try updating OpenVINO to `2019_R3.1` first.

**Comment by VanDavv** [comment]
It's fixed now in main, all results are returned, which are above the confidence threshold
