### ISSUE TITLE
Blobconverter

### ISSUE THREAD

**Issue by Erol444** [luxonis/depthai-tutorials#10]
[In tutorial](https://docs.luxonis.com/projects/api/en/latest/tutorials/hello_world/#install-pip-dependencies), there's no mention about installing **blobconverter**. Add it there or edit to use the requirements.txt (update version of blobconverter).

![image](https://user-images.githubusercontent.com/18037362/137646988-7bb7c1c0-2009-4b75-8452-8138f73826e6.png)

**Comment by VanDavv** [comment]
Added both:
- updated requirements in tutorials to latest releases - https://github.com/luxonis/depthai-tutorials/commit/c5be82339fa78b87a5553615058fa821abe24db5
- added blobconverter mention in the docs - https://github.com/luxonis/depthai-python/pull/419
