### ISSUE TITLE
Transformed from CHW channel order into HWC in hello_world.py

### ISSUE THREAD

**Issue by silent-code** [luxonis/depthai-tutorials#7]
Can you explain two discrepancies with this hello_world.py tutorial example please? 

1) On line 65 in hello_world.py the frame is transformed from CHW to HWC order. However, the [openvino toolkit documentation](https://docs.openvinotoolkit.org/latest/omz_models_model_mobilenet_ssd.html) states that the required order for the modified mobilenet-ssd model is CHW.  

2) Furthermore, I don't see  in this same hello_world.py example where the frame RGB is reversed to BGR as required?

I've noted that in [this](https://github.com/luxonis/depthai-experiments/blob/master/gen2-coronamask/main.py) example that the conversion is HWC -> CHW (line 152) and RBG -> BGR (line 154) when using recorded video.

Thanks in advance for your help.

Tim

**Comment by Luxonis-Brandon** [comment]
Thanks, Tim - and sorry for the confusion here.  

I'm not immediately sure but I think @VanDavv should know.

**Comment by silent-code** [comment]
Hey Brandon, 

Erik helped me sort it out [here](https://discuss.luxonis.com/d/231-chw-to-hwc-and-rbg-to-bgr-order-transforms-for-models) on the Luxonis discussion board.
